"""tags

Revision ID: 0e2557fdb1a5
Revises: 0556ae6a92b4
Create Date: 2020-07-09 02:47:17.507223

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0e2557fdb1a5"
down_revision = "0556ae6a92b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publication",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author", sa.Integer(), nullable=False),
        sa.Column("type_of", sa.String(length=256), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("slug", sa.String(length=256), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("comments_count", sa.Integer(), nullable=True),
        sa.Column("reactions_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.Date(), nullable=True),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("edited_at", sa.Date(), nullable=True),
        sa.Column("cover_image", sa.String(length=256), nullable=True),
        sa.Column("social_image", sa.String(length=256), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "publication_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["department_id"], ["publication.id"]),
        sa.PrimaryKeyConstraint("id", "department_id"),
    )
    op.drop_table("publications")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publications",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("slug", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("comments_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("reactions_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("published_at", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("created_at", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("edited_at", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column(
            "cover_image", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column(
            "social_image", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("body_html", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "type_of", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column("author", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="publications_pkey"),
        sa.UniqueConstraint("slug", name="publications_slug_key"),
        sa.UniqueConstraint("title", name="publications_title_key"),
    )
    op.drop_table("publication_tags")
    op.drop_table("tag")
    op.drop_table("publication")
    # ### end Alembic commands ###
