"""author

Revision ID: 9a08d907be80
Revises: 3703bfcf5880
Create Date: 2020-07-03 22:35:17.095274

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9a08d907be80"
down_revision = "3703bfcf5880"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("publications", sa.Column("author", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("publications", "author")
    # ### end Alembic commands ###
