apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: minikube-ingress
  annotations:
spec:
  rules:
  - host: hello.world
    http:
      paths:
      - path: /
        backend:
          serviceName: auth-frontend
          servicePort: 3000
      - path: /api/v1
        backend:
          serviceName: auth-backend
          servicePort: 5000
