"""changes to user model

Revision ID: abdc87e32431
Revises: 2527b1a68e32
Create Date: 2020-07-28 13:41:17.813120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "abdc87e32431"
down_revision = "2527b1a68e32"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_refresh_token_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("users_refresh_token_key", "users", ["refresh_token"])
    # ### end Alembic commands ###
