apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-backend
  labels:
    app: auth-backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-backend
  template:
    metadata:
      labels:
        app: auth-backend
    spec:
      containers:
      - name: auth-backend
        image: auth-backend:1
        imagePullPolicy: Never
        env:
        - name: CELERY_BROKER_URL
          value: amqp://guest:guest@rabbitmq:5672
        - name: CELERY_RESULT_URL
          value: redis://redis:6379/1
        - name: POSTGRES_USERNAME
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DATABASE
          value: "postgres"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: BAREMETAL_INSTANCE
          value: "http://3.10.22.115:4444/wd/hub"
