version: "2.2"

services:
  # Selenium hub
  selenium_hub:
    image: selenium/hub:3.14.0-curium
    ports:
      - 4444:4444

  samsung_galaxy_6:
    image: budtmo/docker-android-x86-8.1
    privileged: true
    scale: 10
    depends_on:
      - selenium_hub
    ports:
      - 6080:6080
    environment:
      - DEVICE=Samsung Galaxy S6
      - CONNECT_TO_GRID=true
      - APPIUM=true
      - SELENIUM_HOST=selenium_hub
      - MOBILE_WEB_TEST=true
    volumes:
    - ./provision/Nike.apk:/provision/Nike.apk
